#!/usr/bin/env python3
"""Replay selected finite-field gap systems; solver output lives only in a temporary directory."""
import argparse
import csv
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import time
import re
from math import comb
from kernel import kappa_formula, stratum_system, check_weighted_homogeneous, poly_to_str

def gaussian_binomial(g, s):
    """coefficient list of [g choose s]_t"""
    def mulp(a, b):
        r = [0] * (len(a) + len(b) - 1)
        for i, x in enumerate(a):
            if x:
                for j, y in enumerate(b):
                    r[i + j] += x * y
        return r
    def divp(a, b):  # exact division
        a = a[:]; q = [0] * (len(a) - len(b) + 1)
        for k in range(len(q) - 1, -1, -1):
            q[k] = a[k + len(b) - 1] // b[-1]
            for j, y in enumerate(b):
                a[k + j] -= q[k] * y
        assert all(x == 0 for x in a)
        return q
    num = [1]
    for j in range(1, s + 1):
        f = [0] * (g - s + j + 1); f[0] = 1; f[-1] = -1
        num = mulp(num, f)
    for j in range(1, s + 1):
        f = [0] * (j + 1); f[0] = 1; f[-1] = -1
        num = divp(num, f)
    return num

def parse_leading_ideal(path, s):
    txt = open(path).read()
    body = txt[txt.index("["):]
    body = body[1:body.rindex("]")]
    lms = []
    for term in body.replace("\n", "").split(","):
        term = term.strip()
        if not term:
            continue
        m = [0] * s
        if term != "1":
            for fac in term.split("*"):
                mm = re.fullmatch(r"c(\d+)\^(\d+)", fac)
                assert mm, (term, fac)
                m[int(mm.group(1)) - 1] = int(mm.group(2))
        lms.append(tuple(m))
    return lms

def staircase_hilbert(lms, s, wmax, node_limit=2000000):
    """Hilbert function (by weight wt c_i = i) of the monomial ideal generated by lms.
    Returns None if the staircase is not contained in weights <= wmax+s (or is too large)."""
    import numpy as np
    idx = {}
    for m in lms:
        for k in range(s):
            if m[k] > 0:
                idx.setdefault((k, m[k]), []).append(m)
    idx = {key: np.array(v, dtype=np.int32) for key, v in idx.items()}
    if any(all(e == 0 for e in m) for m in lms):
        return {}
    hf = {}
    count = 0
    stack = [(tuple([0] * s), 0, 0)]  # monomial, min variable index allowed, weight
    while stack:
        m, kmin, w = stack.pop()
        hf[w] = hf.get(w, 0) + 1
        count += 1
        if count > node_limit or w > wmax + s:
            return None
        for k in range(kmin, s):
            m2 = list(m); m2[k] += 1
            gens = idx.get((k, m2[k]))
            # m is standard, so m2 lies in the monomial ideal iff a generator with exponent exactly m2[k]
            # in the variable c_{k+1} divides m2
            if gens is not None and bool(np.any(np.all(gens <= np.array(m2, dtype=np.int32), axis=1))):
                continue
            stack.append((tuple(m2), k, w + k + 1))
    return hf


def is_prime(n):
    if n < 2:
        return False
    if n % 2 == 0:
        return n == 2
    return all(n % d for d in range(3, int(n**0.5)+1, 2))


def check_stratum(q, g, s, executable, timeout=1500, threads=1, memory_gb=32):
    if not (is_prime(q) and q > g >= 2 and g % 2 == 0 and 1 <= s <= g):
        raise ValueError('Require an odd prime q, even 2 <= g < q, and 1 <= s <= g')
    started = time.monotonic()
    table = kappa_formula(g, s, mod=q)
    equations = stratum_system(g, s, table, p=q)
    check_weighted_homogeneous(equations, g, s)
    names = [f'c{i}' for i in range(1, s+1)]
    polynomials = [poly_to_str(f, names) for f in equations if f]
    record = {'q':q, 'g':g, 's':s, 'engine':'msolve', 'linear_algebra':2,
              'n_zero_generators':sum(not f for f in equations)}
    if not polynomials:
        return {**record, 'rigid':False, 'reason':'all generators vanish'}
    text = ','.join(names)+'\n'+str(q)+'\n'+',\n'.join(polynomials)+'\n'
    record['input_sha256'] = hashlib.sha256(text.encode()).hexdigest()

    def set_limit():
        if memory_gb:
            import resource
            size = memory_gb*1024**3
            resource.setrlimit(resource.RLIMIT_AS, (size, size))

    with tempfile.TemporaryDirectory(prefix='rigidity-gap-') as directory:
        input_path = Path(directory)/'input.ms'
        output_path = Path(directory)/'leading.out'
        input_path.write_text(text)
        run = subprocess.run(
            [executable,'-g','1','-l','2','-t',str(threads),'-f',str(input_path),'-o',str(output_path)],
            stdout=subprocess.DEVNULL, stderr=subprocess.PIPE, text=True,
            timeout=timeout, preexec_fn=set_limit if os.name=='posix' else None,
        )
        if run.returncode:
            raise RuntimeError(f'msolve exited {run.returncode}: {run.stderr[-2000:]}')
        leading = parse_leading_ideal(output_path, s)
        if not leading or any(sum(m)==0 for m in leading):
            raise RuntimeError('Unexpected empty or unit leading ideal for a homogeneous origin-containing system')
        pure = []
        for index in range(s):
            exponents = [m[index] for m in leading if m[index]>0 and sum(m)==m[index]]
            pure.append(min(exponents) if exponents else None)
        record.update(rigid=all(x is not None for x in pure), pure_powers=pure, n_lm=len(leading))
        if record['rigid']:
            top = s*(g-s)
            hilbert = staircase_hilbert(leading, s, top)
            expected = gaussian_binomial(g, s)
            valid = hilbert is not None and max(hilbert)==top and all(hilbert.get(w,0)==expected[w] for w in range(top+1))
            record.update(hilbert_ok=valid, vdim=sum(hilbert.values()) if hilbert else None,
                          expected_vdim=comb(g,s))
            if not valid:
                raise RuntimeError('The computed Hilbert function failed the independent Gaussian-binomial check')
    record['elapsed_seconds'] = round(time.monotonic()-started, 3)
    return record


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--q', type=int)
    parser.add_argument('--g', type=int)
    parser.add_argument('--stratum', type=int)
    parser.add_argument('--all', action='store_true', help='Replay every positive-gap stratum used by coverage.csv')
    parser.add_argument('--msolve', default=os.environ.get('MSOLVE_BIN','msolve'))
    parser.add_argument('--threads', type=int, default=1)
    parser.add_argument('--timeout', type=int, default=1500, help='Seconds per stratum')
    parser.add_argument('--memory-gb', type=int, default=32, help='Per-process address-space cap on POSIX; zero disables it')
    parser.add_argument('--output', type=Path, help='Write fresh JSON-line results here; otherwise print them only')
    parser.add_argument('--expect-nonrigid', action='store_true', help='Check a known bad pair as a negative control')
    args = parser.parse_args()
    executable = shutil.which(args.msolve)
    if not executable:
        parser.error('msolve was not found; pass --msolve /path/to/msolve')
    if args.threads<1 or args.timeout<1 or args.memory_gb<0:
        parser.error('threads and timeout must be positive, memory-gb nonnegative')
    if args.all:
        if args.q is not None or args.g is not None or args.stratum is not None or args.expect_nonrigid:
            parser.error('--all cannot be combined with pair, stratum, or negative-control options')
        with Path(__file__).with_name('coverage.csv').open() as f:
            pairs = {(int(r['q']),int(r['g'])) for r in csv.DictReader(f) if int(r['g'])>0}
        tasks = [(q,g,s) for q,g in sorted(pairs) for s in range(1,g+1)]
    else:
        if args.q is None or args.g is None:
            parser.error('Pass --q Q --g G, optionally --stratum S, or --all')
        strata = [args.stratum] if args.stratum is not None else range(1,args.g+1)
        tasks = [(args.q,args.g,s) for s in strata]
    if args.output:
        args.output.parent.mkdir(parents=True,exist_ok=True)
    stream = args.output.open('w') if args.output else None
    try:
        for q,g,s in tasks:
            record = check_stratum(q,g,s,executable,args.timeout,args.threads,args.memory_gb)
            line = json.dumps(record,sort_keys=True)
            print(line,flush=True)
            if stream:
                stream.write(line+'\n'); stream.flush()
            expected_rigid = not args.expect_nonrigid
            if record['rigid'] != expected_rigid:
                raise RuntimeError(f'Unexpected origin-support verdict for {(q,g,s)}')
    finally:
        if stream:
            stream.close()


if __name__=='__main__':
    main()
